version: "3.3"
services:
  db:
    image: postgres:12.0-alpine
    ports:
      - 5434:5432
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: flask_db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@email.com
      PGADMIN_DEFAULT_PASSWORD: root

  flask:
    build: ./flask
    ports:
      - 5000:5000
    volumes:
      - ./flask:/app
    depends_on:
      - db
      
  reactjs:
    container_name: autenticacao-flask_reactjs
    build:
      context: ./front-autenticacao
      dockerfile: Dockerfile
    volumes:
      - './front-autenticacao:/app'
      - './front-autenticacao/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
